// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhU-UxQvz_os_lKQ2zJoF_xtavq8kjhg',
    appId: '1:425154750765:web:8daa40fd96e16cc3838ba4',
    messagingSenderId: '425154750765',
    projectId: 'phoneverification-6099b',
    authDomain: 'phoneverification-6099b.firebaseapp.com',
    storageBucket: 'phoneverification-6099b.firebasestorage.app',
    measurementId: 'G-NN54N89XH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvtU6I8PqH1lSSRHI35_z5DXzbYjlAak',
    appId: '1:425154750765:android:9f4060d6348a6561838ba4',
    messagingSenderId: '425154750765',
    projectId: 'phoneverification-6099b',
    storageBucket: 'phoneverification-6099b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB61vG9E2h3NSWXDBBLJlYRW2R-i1VRCi8',
    appId: '1:425154750765:ios:0093fc6bc03057f7838ba4',
    messagingSenderId: '425154750765',
    projectId: 'phoneverification-6099b',
    storageBucket: 'phoneverification-6099b.firebasestorage.app',
    iosClientId: '425154750765-tr2u0poegl6kvg3jmogej65crip10e7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.digimeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB61vG9E2h3NSWXDBBLJlYRW2R-i1VRCi8',
    appId: '1:425154750765:ios:0093fc6bc03057f7838ba4',
    messagingSenderId: '425154750765',
    projectId: 'phoneverification-6099b',
    storageBucket: 'phoneverification-6099b.firebasestorage.app',
    iosClientId: '425154750765-tr2u0poegl6kvg3jmogej65crip10e7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.digimeds',
  );
}
